# Generated by Django 5.2.3 on 2025-06-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud_article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('following_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='following_user', serialize=False, to='crud_article.auteur')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='followed_user_set', to='crud_article.auteur')),
            ],
            options={
                'db_table': 'follows',
                'unique_together': {('following_user', 'followed_user')},
            },
        ),
    ]
