# Generated by Django 5.2.3 on 2025-06-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
