# Generated by Django 5.2.3 on 2025-07-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_article', '0002_remove_article_image_url_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
