# Generated by Django 5.2.3 on 2025-07-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_article', '0003_article_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auteurs/'),
        ),
    ]
