# Generated by Django 5.2.3 on 2025-07-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_article', '0004_auteur_bio_auteur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='profession',
            field=models.TextField(blank=True, default='Author', null=True),
        ),
    ]
