# Generated by Django 5.2.3 on 2025-07-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_article', '0005_auteur_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Categorie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
