# Generated by Django 5.2.3 on 2025-07-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_article', '0006_article_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auteur',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
